### ISSUE TITLE
cannot open file `include/rocksdb/version.h'

### ISSUE THREAD

**Issue by prox443** [LatinCash/latincash#1]
Hi,
When i put command: cmake .. and /build/

I have:

> -- BUILD TESTS: enabled
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   system
> --   filesystem
> --   thread
> --   date_time
> --   chrono
> --   regex
> --   serialization
> --   program_options
> --   atomic
> -- Found Git: /usr/bin/git
> awk: fatal: cannot open file `include/rocksdb/version.h' for reading (No such file or directory)
> cat: include/rocksdb/version.h: No such file or directory
> 

Have you an idea to resolve this issue ?
Thk.

**Comment by LatinCash** [comment]
I was checking the files and found that some of them were missing.
Can you try to compile again?
Report me if u have found any other missing files.

**Comment by LatinCash** [comment]
Compilation is ok now

**Comment by prox443** [comment]
Perfect 👍
